import { useState, type FormEvent } from 'react';
import { X, Plus, Trash2, FileText, Send, Zap } from 'lucide-react';
import { InventoryItem, PurchaseOrder, PurchaseOrderItem } from '../types';
import { generatePONumber, formatCurrency } from '../utils/stockUtils';

interface CreatePOModalProps {
  isOpen: boolean;
  onClose: () => void;
  items: InventoryItem[];
  recipientEmail: string;
  onCreatePO: (po: PurchaseOrder, dispatchNow: boolean) => Promise<void>;
}

export function CreatePOModal({
  isOpen,
  onClose,
  items,
  recipientEmail,
  onCreatePO,
}: CreatePOModalProps) {
  const [supplierName, setSupplierName] = useState('Apex Semiconductor Direct');
  const [supplierEmail, setSupplierEmail] = useState('orders@apexsemicon.com');
  const [selectedItemId, setSelectedItemId] = useState(items[0]?.id || '');
  const [orderQty, setOrderQty] = useState(50);
  const [lineItems, setLineItems] = useState<PurchaseOrderItem[]>([]);
  const [notes, setNotes] = useState('Standard stock replenishment order.');
  const [dispatchNow, setDispatchNow] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (!isOpen) return null;

  const handleAddLineItem = () => {
    const item = items.find((i) => i.id === selectedItemId);
    if (!item) return;

    // Check if already in lines
    const existingIndex = lineItems.findIndex((l) => l.itemId === item.id);
    if (existingIndex >= 0) {
      const updated = [...lineItems];
      updated[existingIndex].orderQty += orderQty;
      updated[existingIndex].totalCost = Number(
        (updated[existingIndex].orderQty * item.unitCost).toFixed(2)
      );
      setLineItems(updated);
    } else {
      const lineTotal = Number((orderQty * item.unitCost).toFixed(2));
      const newLine: PurchaseOrderItem = {
        itemId: item.id,
        sku: item.sku,
        name: item.name,
        currentQty: item.quantity,
        orderQty,
        unitCost: item.unitCost,
        totalCost: lineTotal,
        supplierName: item.supplier.name,
        supplierEmail: item.supplier.email,
      };
      setLineItems([...lineItems, newLine]);
      setSupplierName(item.supplier.name);
      setSupplierEmail(item.supplier.email);
    }
  };

  const handleRemoveLine = (idx: number) => {
    setLineItems(lineItems.filter((_, i) => i !== idx));
  };

  const totalAmount = Number(
    lineItems.reduce((acc, curr) => acc + curr.totalCost, 0).toFixed(2)
  );

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (lineItems.length === 0) return;

    setIsSubmitting(true);
    try {
      const now = new Date();
      const formattedDate = `${now.toISOString().split('T')[0]} ${now.toTimeString().substring(0, 5)}`;

      const newPO: PurchaseOrder = {
        id: `po-${Date.now()}`,
        poNumber: generatePONumber(),
        createdAt: formattedDate,
        status: 'draft',
        items: lineItems,
        totalAmount,
        supplierName,
        supplierEmail,
        recipientEmail,
        notes,
        autoGenerated: false,
      };

      await onCreatePO(newPO, dispatchNow);
      onClose();
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs">
      <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-5 border-b border-slate-100 sticky top-0 bg-white dark:bg-slate-800 z-10">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-bold text-slate-900 dark:text-white text-base">Generate Purchase Order</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">Draft PO and dispatch notification via Zapier webhook</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-slate-100 dark:bg-slate-800/50 hover:bg-slate-200 text-slate-600 dark:text-slate-400 flex items-center justify-center transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-5 text-xs">
          {/* Supplier Info */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Supplier / Vendor Name</label>
              <input
                type="text"
                required
                value={supplierName}
                onChange={(e) => setSupplierName(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-600"
              />
            </div>
            <div>
              <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Supplier Contact Email</label>
              <input
                type="email"
                required
                value={supplierEmail}
                onChange={(e) => setSupplierEmail(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-600"
              />
            </div>
          </div>

          {/* Add Item Line Control */}
          <div className="bg-slate-50 dark:bg-slate-900 dark:bg-slate-950 p-3.5 rounded-xl border border-slate-200 dark:border-slate-700 space-y-3">
            <h4 className="font-bold text-slate-800 dark:text-slate-200 text-[11px] uppercase tracking-wider">
              Add Inventory SKU to Order
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
              <div className="sm:col-span-2">
                <select
                  value={selectedItemId}
                  onChange={(e) => {
                    setSelectedItemId(e.target.value);
                    const item = items.find((i) => i.id === e.target.value);
                    if (item) {
                      setSupplierName(item.supplier.name);
                      setSupplierEmail(item.supplier.email);
                    }
                  }}
                  className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800"
                >
                  {items.map((i) => (
                    <option key={i.id} value={i.id}>
                      {i.name} ({i.sku}) - On hand: {i.quantity}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex items-center gap-2">
                <input
                  type="number"
                  min="1"
                  value={orderQty}
                  onChange={(e) => setOrderQty(Math.max(1, parseInt(e.target.value) || 1))}
                  className="w-20 px-2 py-2 rounded-lg border border-slate-300 dark:border-slate-600 font-mono font-bold text-center bg-white dark:bg-slate-800"
                  title="Quantity to order"
                />
                <button
                  type="button"
                  onClick={handleAddLineItem}
                  className="flex-1 flex items-center justify-center gap-1 py-2 px-3 bg-slate-900 dark:bg-slate-950 hover:bg-slate-800 text-white rounded-lg font-semibold"
                >
                  <Plus className="w-3.5 h-3.5" />
                  <span>Add Line</span>
                </button>
              </div>
            </div>
          </div>

          {/* Line Items Table */}
          <div className="space-y-2">
            <span className="font-bold text-slate-800 dark:text-slate-200 block">Purchase Order Lines ({lineItems.length})</span>
            {lineItems.length === 0 ? (
              <div className="py-6 text-center text-slate-400 border border-dashed border-slate-200 dark:border-slate-700 rounded-lg">
                No items added yet. Select an inventory item above and click &quot;Add Line&quot;.
              </div>
            ) : (
              <div className="border border-slate-200 dark:border-slate-700 rounded-lg overflow-hidden">
                <table className="w-full text-left">
                  <thead className="bg-slate-50 dark:bg-slate-900 dark:bg-slate-950 border-b border-slate-200 dark:border-slate-700 font-semibold text-slate-600 dark:text-slate-400">
                    <tr>
                      <th className="py-2 px-3">Item</th>
                      <th className="py-2 px-2 text-center">Order Qty</th>
                      <th className="py-2 px-3 text-right">Cost</th>
                      <th className="py-2 px-3 text-right">Total</th>
                      <th className="py-2 px-2 text-center"></th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {lineItems.map((line, idx) => (
                      <tr key={idx}>
                        <td className="py-2 px-3 font-medium text-slate-900 dark:text-white">
                          {line.name} <span className="font-mono text-[10px] text-slate-500 dark:text-slate-400">({line.sku})</span>
                        </td>
                        <td className="py-2 px-2 text-center font-bold text-blue-600">
                          {line.orderQty}
                        </td>
                        <td className="py-2 px-3 text-right">{formatCurrency(line.unitCost)}</td>
                        <td className="py-2 px-3 text-right font-bold">{formatCurrency(line.totalCost)}</td>
                        <td className="py-2 px-2 text-center">
                          <button
                            type="button"
                            onClick={() => handleRemoveLine(idx)}
                            className="text-slate-400 hover:text-red-500"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Total */}
          {lineItems.length > 0 && (
            <div className="flex justify-between items-center p-3 bg-slate-50 dark:bg-slate-900 dark:bg-slate-950 rounded-lg font-bold text-sm text-slate-900 dark:text-white border border-slate-200 dark:border-slate-700">
              <span>Order Grand Total</span>
              <span>{formatCurrency(totalAmount)}</span>
            </div>
          )}

          {/* Notes */}
          <div>
            <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Procurement Notes / Instructions</label>
            <textarea
              rows={2}
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-600"
            />
          </div>

          {/* Dispatch to Zapier toggle */}
          <label className="flex items-center gap-2.5 cursor-pointer p-3 rounded-lg bg-amber-50/60 border border-amber-200">
            <input
              type="checkbox"
              checked={dispatchNow}
              onChange={(e) => setDispatchNow(e.target.checked)}
              className="w-4 h-4 rounded text-amber-600 focus:ring-amber-500"
            />
            <div>
              <span className="font-bold text-amber-950 block">Dispatch to Zapier Webhook immediately</span>
              <span className="text-amber-800 text-[11px]">
                Sends payload to email notification endpoint (<span className="font-mono">{recipientEmail}</span>)
              </span>
            </div>
          </label>

          {/* Actions */}
          <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:bg-slate-800/50 rounded-lg font-medium transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={lineItems.length === 0 || isSubmitting}
              className="flex items-center gap-1.5 px-5 py-2.5 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white rounded-lg font-semibold shadow-xs transition-colors cursor-pointer"
            >
              <Zap className="w-3.5 h-3.5 text-amber-300" />
              <span>{isSubmitting ? 'Generating...' : 'Generate Purchase Order'}</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
