import { InventoryItem, PurchaseOrder, PurchaseOrderItem, StockStatus } from '../types';

/**
 * Business Rule: Stock Status Classification
 * - CRITICAL: Quantity <= 0 (Stockout) OR Quantity <= minThreshold * 0.5 (≤50% of threshold: imminent stockout danger)
 * - LOW: Quantity <= minThreshold (Breached reorder safety point)
 * - HEALTHY: Quantity > minThreshold
 */
export function calculateStockStatus(quantity: number, minThreshold: number): StockStatus {
  if (quantity <= 0) return 'critical';
  if (quantity <= minThreshold * 0.5) return 'critical';
  if (quantity <= minThreshold) return 'low';
  return 'healthy';
}

/**
 * Currency Formatter
 * Standard US Dollar representation with strict 2-decimal precision.
 */
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

/**
 * Client-fallback PO number generator (server generates authoritative sequential numbers)
 */
export function generatePONumber(): string {
  const year = new Date().getFullYear();
  const randomNum = Math.floor(1000 + Math.random() * 9000);
  return `PO-${year}-${randomNum}`;
}

/**
 * Automated Purchase Order Builder
 * - Groups items by supplier so each vendor receives an independent, consolidated PO.
 * - Order Quantity = Target Stock - On Hand (Deficit), bounded by a minimum replenishment buffer of 120% minThreshold.
 * - Line Total = Math.round(orderQty * wholesaleUnitCost * 100) / 100 (cents precision).
 */
export function buildAutomatedPurchaseOrder(
  itemsToReorder: InventoryItem[],
  recipientEmail: string,
  autoGenerated = true
): PurchaseOrder[] {
  const groupedBySupplier = new Map<string, InventoryItem[]>();

  for (const item of itemsToReorder) {
    const supName = item.supplier.name || 'Primary Supplier';
    if (!groupedBySupplier.has(supName)) {
      groupedBySupplier.set(supName, []);
    }
    groupedBySupplier.get(supName)!.push(item);
  }

  const generatedPOs: PurchaseOrder[] = [];

  groupedBySupplier.forEach((items, supplierName) => {
    const primarySupplier = items[0].supplier;
    const poItems: PurchaseOrderItem[] = items.map((item) => {
      // Unit Deficit Formula: Max(0, Target Stock - On Hand)
      const deficit = Math.max(0, item.targetStock - item.quantity);
      // Ensure at least enough to reach safety target or 120% of minThreshold
      const neededQty = Math.max(deficit, Math.ceil(item.minThreshold * 1.2), 1);
      // Cost calculation strictly in cents to avoid IEEE 754 float drift
      const totalCost = Math.round(neededQty * item.unitCost * 100) / 100;

      return {
        itemId: item.id,
        sku: item.sku,
        name: item.name,
        currentQty: item.quantity,
        orderQty: neededQty,
        unitCost: item.unitCost,
        totalCost,
        supplierName: item.supplier.name,
        supplierEmail: item.supplier.email,
      };
    });

    const totalAmount = Math.round(
      poItems.reduce((acc, curr) => acc + curr.totalCost, 0) * 100
    ) / 100;

    const now = new Date();
    const formattedDate = `${now.toISOString().split('T')[0]} ${now.toTimeString().substring(0, 5)}`;

    const po: PurchaseOrder = {
      id: `po-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      poNumber: generatePONumber(),
      createdAt: formattedDate,
      status: 'draft',
      items: poItems,
      totalAmount,
      supplierName,
      supplierEmail: primarySupplier.email,
      recipientEmail: recipientEmail || 'procurement@company.com',
      notes: `Automated reorder triggered by low-inventory threshold breach. Items require replenishment to target safety stock level.`,
      autoGenerated,
    };

    generatedPOs.push(po);
  });

  return generatedPOs;
}
