export type StockStatus = 'healthy' | 'low' | 'critical';

export interface SupplierInfo {
  name: string;
  email: string;
  phone: string;
  leadTimeDays: number;
}

export interface InventoryItem {
  id: string;
  sku: string;
  name: string;
  category: string;
  warehouse: string;
  quantity: number;
  minThreshold: number;
  targetStock: number;
  unitCost: number;
  unitPrice: number;
  supplier: SupplierInfo;
  lastRestocked: string;
  isEssential: boolean;
  status: StockStatus;
  notes?: string;
}

export interface StockMovement {
  id: string;
  itemId: string;
  itemName: string;
  sku: string;
  type: 'sale' | 'restock' | 'adjustment' | 'po_received';
  quantityChange: number;
  previousQty: number;
  newQty: number;
  timestamp: string;
  note: string;
}

export interface PurchaseOrderItem {
  itemId: string;
  sku: string;
  name: string;
  currentQty: number;
  orderQty: number;
  unitCost: number;
  totalCost: number;
  supplierName: string;
  supplierEmail: string;
}

export type POStatus = 'draft' | 'dispatched_zapier' | 'dispatch_failed' | 'approved' | 'received';

export interface PurchaseOrder {
  id: string;
  poNumber: string;
  createdAt: string;
  status: POStatus;
  items: PurchaseOrderItem[];
  totalAmount: number;
  supplierName: string;
  supplierEmail: string;
  recipientEmail: string;
  zapierDispatchedAt?: string;
  zapierStatus?: 'simulated' | 'success' | 'failed';
  zapierHttpCode?: number;
  notes: string;
  autoGenerated: boolean;
}

export interface ZapierSettings {
  autoTriggerOnLowStock: boolean;
  autoTriggerOnlyEssential: boolean;
  sendEmailCopy: boolean;
  notificationPrefix: string;
  webhookUrl?: string;
}

export interface WebhookLog {
  id: string;
  timestamp: string;
  poNumber: string;
  targetUrl: string; // Keep this as just '***' or 'configured webhook' for the frontend log
  recipientEmail: string; // Keep this as just '***' or 'configured email'
  status: 'success' | 'failed' | 'simulated';
  httpCode?: number;
  responsePreview?: string;
  payload: any;
}

export interface CategorySales {
  category: string;
  revenue: number;
  units: number;
  profit: number;
}

export interface MonthlySales {
  month: string;
  revenue: number;
  cost: number;
  profit: number;
  units: number;
}

export interface QuarterlyTrendReport {
  id: string;
  quarter: string;
  year: number;
  periodLabel: string;
  totalRevenue: number;
  cogs: number;
  grossProfit: number;
  profitMarginPercent: number;
  unitsSold: number;
  inventoryTurnoverRate: number;
  carryingCostEstimate: number;
  topPerformingItems: { sku: string; name: string; revenue: number; units: number }[];
  categoryBreakdown: CategorySales[];
  monthlyBreakdown: MonthlySales[];
  growthComparedToPreviousQ: number; // percentage
}
